name: not_flutter_manifest
description: Not not-node manifest interface client side for Flutter
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  not_flutter_path:
    git:
      url: https://github.com/interrupter/not_flutter_path.git
  http: ^0.13.4
  dio: ^4.0.6